<a href="https://colab.research.google.com/github/hkumarrai1/90-days-Web-development-Challenge/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**->> Understanding** **numpy**

In [ ]:
import numpy as np

a=np.array([1,2,3,5,5] ,dtype='f')
b=np.array((4,5,6,7))
print(a)
print(a.dtype)
print(b)
print(type(a))
print(type(b))


[1. 2. 3. 5. 5.]
float32
[4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**->> ndim() property to know the dimension**

In [ ]:
a=np.array([[1,2,3,5,5],[3,4,6,7,7]] ,dtype='f')
b=np.array([[[1,2,3],[4,5,6],[1,4,5]],[[6,7,8],[4,5,6],[5,6,7]]])
print(a.ndim)
print(b.ndim)
print(a[0,2],a[0,3])
print(b[1,2,2])

2
3
3.0 5.0
7


**->>> shape()**

In [ ]:
b=np.array([[[1,2,3],[4,5,6],[1,4,5]],[[6,7,8],[4,5,6],[5,6,7]]])
print(b.shape)
print(b.size)
print(b.nbytes)

(2, 3, 3)
18
144


**->> Numpy(np.arrange,reshape,random)**

In [ ]:
A=np.arange(20,100,2)
print(A)
print(A.ndim)
B=np.random.permutation(np.arange(10))
print(B)
C=np.random.rand(2,3,4,5)
print(C)
print(C.shape)
print(C.size)
print(C.ndim)
d=np.arange(20).reshape(5,4)
print(d)
print(d.shape)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
1
[2 3 9 8 7 5 0 6 4 1]
[[[[0.16602153 0.06331882 0.76138699 0.33636821 0.05389715]
   [0.25358625 0.53139726 0.99489186 0.58131308 0.15603056]
   [0.14784384 0.09677902 0.50467686 0.11860301 0.37145251]
   [0.82206919 0.04096864 0.80924392 0.29180583 0.44487966]]

  [[0.4605734  0.60420989 0.98563307 0.95170953 0.29306737]
   [0.4738862  0.08584156 0.07296625 0.90462981 0.08491389]
   [0.69101875 0.87902634 0.92364658 0.44383963 0.03868124]
   [0.49206636 0.17602646 0.59965491 0.05260272 0.34721118]]

  [[0.43439478 0.84912315 0.0156437  0.0261967  0.34857845]
   [0.62589708 0.85546415 0.26842886 0.86776494 0.9790764 ]
   [0.04980279 0.07806966 0.56088645 0.56924122 0.0462565 ]
   [0.49095384 0.20186818 0.57158397 0.56984781 0.43884582]]]


 [[[0.59470769 0.06794343 0.59776506 0.15296738 0.85203315]
   [0.08045806 0.00539312 0.29294032 0.91910874 0.78424856]
   [0

**->>> Numpy(Slicing)**

In [ ]:
A=np.arange(100)
b=A[3:10]
print(b)
b[0]=-788
print(b[0])
print(A)
b=A[3:10].copy()
print(b)
b[0]=-788
print(b[0])
print(A)


print(A[::5])
print(A[::-5])
print(np.where(A==42)[0][0])

[3 4 5 6 7 8 9]
-788
[   0    1    2 -788    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99]
[-788    4    5    6    7    8    9]
-788
[   0    1    2 -788    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
  

**Numpy (More Indexing)**

In [ ]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean mask
mask = arr > 5

# Apply the mask to the array
masked_arr = arr[mask]

# Print the original array, the mask, and the masked array
print("Original array:", arr)
print("Mask:", mask)
print("Masked array:", masked_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Mask: [False False False False False  True  True  True  True  True]
Masked array: [ 6  7  8  9 10]


**Numpy BroadCasting**

In [ ]:
# Create a NumPy array
arr = np.array([1, 2, 3])

# Create a scalar
scalar = 2

# Perform broadcasting: multiply the array by the scalar
result = arr * scalar

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
arr_1d = np.array([10, 20, 30])

# Perform broadcasting: add the 1D array to the 2D array
result_broadcast = arr_2d + arr_1d

# Print the results
print("Original array:", arr)
print("Scalar:", scalar)
print("Result of scalar broadcasting:", result)
print("\nOriginal 2D array:", arr_2d)
print("Original 1D array:", arr_1d)
print("Result of array broadcasting:", result_broadcast)

Original array: [1 2 3]
Scalar: 2
Result of scalar broadcasting: [2 4 6]

Original 2D array: [[1 2 3]
 [4 5 6]]
Original 1D array: [10 20 30]
Result of array broadcasting: [[11 22 33]
 [14 25 36]]


In [ ]:
arra1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arra1.ndim,arra1.shape)
arra2=np.array([[6,7,8,9,10],[1,2,3,4,5]])
#these are Universal functions
print(np.hstack((arra1,arra2)))
print(np.vstack((arra1,arra2)))


2 (2, 5)
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 6  7  8  9 10  1  2  3  4  5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
